openapi: 3.0.3
info:
  version: 0.0.1
  title: kotobako Web API
paths:
  /v1/health:
    get:
      operationId: HealthCheck
      tags: 
        - health
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
        400:
          $ref: '#/components/responses/BadRequest'
  /v1/quotes:
    get:
      summary: セリフ一覧 API
      operationId: QuoteList
      tags:
        - quotes 
      responses:
        200:
          description: セリフ一覧を返す
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuoteResponse'
        400:
          $ref: '#/components/responses/BadRequest'
    post:
      summary: セリフ登録 API
      operationId: registerQuote
      tags:
        - quotes 
      requestBody:
        description: セリフ登録データ
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/RegisterQuoteRequest'
      responses:
        204:
          description: セリフを登録する
        400:
          $ref: '#/components/responses/BadRequest'
  /v1/quotes/{quoteId}:
    get:
      summary: セリフ詳細 API
      operationId: QuoteDetail
      tags:
        - quotes
      parameters:
        - in: path
          name: quoteId
          schema:
            type: integer
          required: true
          description: セリフに紐づくID
      responses:
        200:
          description: セリフ詳細を返す
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteResponse'
        400:
          $ref: '#/components/responses/BadRequest'

tags:
    - name: health
      description: ヘルスチェックに使う API 群
    - name: quotes
      description: セリフ一覧を返す API群
components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    HelloResponse:
      type: object
      properties:
        status:
          type: string
          format: ok

    RegisterQuoteRequest:
      description: セリフ登録API のリクエスト
      type: object
      required:
        - sentence
        - description
        - speaker_name
        - quote_source_name
        - quote_media_type
      properties:
        sentence:
          type: string
          description: 文章本体
        speaker_name:
          type: string
          description: 引用元コンテンツの発言者、もしくは作成者(コンテンツによってはNULL が入る場合もあり)
        quote_source_name:
          type: string
          description: 引用元の名前 (本のタイトル、映画、公演名 etc...)
        quote_media_type:
          type: string
          description: 引用元のメディアタイプ(enum 型だが string管理)

    QuoteThumbnailResponse:
      description: セリフ情報一覧取得時に使うレスポンス
      type: object
      required:
        - id
        - sentence
        - quote_source_name 
      properties:
        id:
          type: integer
          description: セリフに紐づくID
        sentence:
          type: string
          description: 文章本体
        quote_source_name:
          type: string
          description: 引用元の名前 (本のタイトル、映画、公演名 etc...)

    QuoteResponse:
      description: セリフ情報詳細
      type: object
      required:
        - id
        - sentence
        - quote_source_name 
        - quote_media_type
        - updatedAt
      properties:
        id:
          type: integer
          description: セリフに紐づくID
        sentence:
          type: string
          description: 文章本体
        speaker_name:
          type: string
          description: 引用元コンテンツの発言者、もしくは作成者(コンテンツによってはNULL が入る場合もあり)
        quote_source_name:
          type: string
          description: 引用元の名前 (本のタイトル、映画、公演名 etc...)
        quote_media_type:
          type: string
          description: 引用元のメディアタイプ(enum 型だが string管理)
        updated_at:
          type: string
          format: date-time
          description: 最終更新日時
        
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          format: please input your error message.
