# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  init:
    deps: [init:go, init:buf]
  init:go:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
      - go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
  init:buf:
    dir: buf
    cmds:
      - yarn
  gen:
    deps: [gen:buf, gen:apidoc]
  gen:buf:
    dir: buf
    cmds:
      - npx buf generate
  gen:apidoc:
    cmds:
      - protoc --doc_out=./doc --doc_opt=html,index.html buf/kotobako/**/*.proto
  clean:
    deps: [clean:backend, clean:frontend]
  clean:backend:
    rm -rf backend/generated
  clean:frontend:
    rm -rf frontend/src/generated

  
